reviewers:
  # The default reviewers
  defaults:
    - code-owners # group

  # Please note reviewers do not need to be restricted to people
  # who have write access. TLs and Emeriti Chairs have write
  # access and Co-chairs have admin access
  # Once a member who does not have "write/push" access, finishes
  # their review, they should assign it to one of the code-owners
  # mentioned below for approval
  groups:
    code-owners:
      - ultrasaurus
      - dshaw
      - pragashj
      - lumjjb
      - TheFoxAtWork
      - JustinCappos
      - achetal01
      - ashutosh-narkar
      - anvega
      - PushkarJ
      - mnm678
      - mlieberman85
      - ragashreeshekar
      - sublimino
      - eddie-knight
    supply-chain-security-reviewers:
      - mnm678
      - mlieberman85
      - anvega
      - lumjjb
      - SantiagoTorres
      - lirantal
    whitepaper-reviewers:
      - PushkarJ
      - ragashreeshekar
      - TheFoxAtWork
      - achetal01
      - ashutosh-narkar
    controls-reviewers:
      - JonZeolla
    assessments-reviewers:
      - eddie-knight

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  'security-whitepaper/**':
    - whitepaper-reviewers # group
  'landscape/**':
    - whitepaper-reviewers #group
  'security-lexicon/**':
    - whitepaper-reviewers #group
  'supply-chain-security/**':
    - supply-chain-security-reviewers #group
  'cloud-native-controls/**':
    - controls-reviewers #group
  'assessments/**':
    - assessments-reviewers #group

options:
  ignore_draft: true #draft PRs are ignored
  ignored_keywords: #PRs with the following keywords in the title are ignored
    - DO NOT REVIEW
    - NOT READY FOR REVIEW
    - WIP
  enable_group_assignment: false #assignment based on group membership of author

  # Randomly pick reviewers up to this number.
  # Do not set this option if you'd like to assign all matching reviewers.
  number_of_reviewers: 3

#More info: https://github.com/necojackarc/auto-request-review/tree/https://github.com/necojackarc/auto-request-review/tree/e08cdffa277d50854744de3f76230260e61c67f4#readme
