repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: tag-security

  # A short description of the repository that will show up on GitHub
  description: 🔐CNCF Security Technical Advisory Group -- secure access, policy control, privacy, auditing, explainability and more!

  # A URL with more information about the repository
  homepage: https://cncf.io/projects
  
  # Collaborators: give specific users access to this repository.
  # Note that the permissions are controlled using CLOWarden in the https://github.com/cncf/people/blob/main/config.yaml file
  # Please create a PR in the https://github.com/cncf/people/ repo to change user access
