repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: sig-security

  # A short description of the repository that will show up on GitHub
  description: 🔐CNCF Special Interest Group on Security -- secure access, policy control, privacy, auditing, explainability and more!

  # A URL with more information about the repository
  homepage: https://cncf.io/projects
  
  # Collaborators: give specific users access to this repository.
collaborators:
  - username: ultrasaurus
    permission: admin

  - username: dshaw
    permission: admin

  - username: pragashj
    permission: admin

    # Security Assessment Facilitator
  - username: JustinCappos
    permission: push
  
    # Triage Team
  - username: lumjjb
    permission: push

  - username: hannibalhuang
    permission: push
    
