name: Auto Request Review

on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  auto-request-review:
    name: Auto Request Review
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps: #Using sha pinning instead of version tag of v0.7.0
      - name: Request review based on which files changed
        uses: necojackarc/auto-request-review@e08cdffa277d50854744de3f76230260e61c67f4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}